PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX oio: <http://www.geneontology.org/formats/oboInOwl#>  
PREFIX obo: <http://purl.obolibrary.org/obo/>  
        
SELECT distinct ?to
WHERE {

        ?to (owl:equivalentClass/(owl:intersectionOf/rdf:rest*/rdf:first))* ?pato .
        ?to (owl:equivalentClass/(owl:intersectionOf/rdf:rest*/rdf:first/owl:someValuesFrom))* ?extClass .
        ?to (owl:equivalentClass/(owl:intersectionOf/rdf:rest*/rdf:first/owl:onProperty))* ?prop .

        ?to1 (owl:equivalentClass/(owl:intersectionOf/rdf:rest*/rdf:first))* ?pato .
        ?to1 (owl:equivalentClass/(owl:intersectionOf/rdf:rest*/rdf:first/owl:someValuesFrom))* ?extClass .
        ?to1 (owl:equivalentClass/(owl:intersectionOf/rdf:rest*/rdf:first/owl:onProperty))* ?prop .
        filter(!isblank(?extClass) && !isblank(?pato))
        filter (?to != ?pato)
        filter (?to != ?extClass)
        filter (?to != ?prop)
        filter (?to != ?to1)  
}